name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5 
          
      - name: Configure Terraform Cloud Token
        env:
          TERRAFORM_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
        run: |
          mkdir -p ~/.terraform.d
          echo "{\"credentials\": {\"app.terraform.io\": {\"token\": \"$TERRAFORM_TOKEN_app_terraform_io\"}}}" > ~/.terraform.d/credentials.tfrc.json   

      - name: Terraform Init
        run: terraform init

       - name: Terraform Plan and Apply
        run: |
          terraform plan -input=false || exit 1
          if [ "${{ github.event_name }}" == "push" ]; then
            terraform apply -auto-approve
          fi
